homePagePermalink: ':moduleGroup/:module'
sourcePagePermalink: ':moduleType/:module/:sourceDocPath'

modules:
  - { name: 'orchid-core',                       sourceDirs: ['../../main/kotlin', '../../main/java'],                                 moduleGroup: 'plugins' }
  - { name: 'orchid-test',                       sourceDirs: '../../../../orchid-test/src/main/kotlin',                                moduleGroup: 'plugins' }
  - { name: 'orchid-archives-feature',           sourceDirs: '../../../../features/orchid-archives-feature/src/main/kotlin',           moduleGroup: 'plugins' }
  - { name: 'orchid-asciidoc-feature',           sourceDirs: '../../../../features/orchid-asciidoc-feature/src/main/kotlin',           moduleGroup: 'plugins' }
  - { name: 'orchid-azure-feature',              sourceDirs: '../../../../features/orchid-azure-feature/src/main/kotlin',              moduleGroup: 'plugins' }
  - { name: 'orchid-bible-feature',              sourceDirs: '../../../../features/orchid-bible-feature/src/main/kotlin',              moduleGroup: 'plugins' }
  - { name: 'orchid-bitbucket-feature',          sourceDirs: '../../../../features/orchid-bitbucket-feature/src/main/kotlin',          moduleGroup: 'plugins' }
  - { name: 'orchid-changelog-feature',          sourceDirs: '../../../../features/orchid-changelog-feature/src/main/kotlin',          moduleGroup: 'plugins' }
  - { name: 'orchid-diagrams-feature',           sourceDirs: '../../../../features/orchid-diagrams-feature/src/main/kotlin',           moduleGroup: 'plugins' }
  - { name: 'orchid-forms-feature',              sourceDirs: '../../../../features/orchid-forms-feature/src/main/kotlin',              moduleGroup: 'plugins' }
  - { name: 'orchid-github-feature',             sourceDirs: '../../../../features/orchid-github-feature/src/main/kotlin',             moduleGroup: 'plugins' }
  - { name: 'orchid-gitlab-feature',             sourceDirs: '../../../../features/orchid-gitlab-feature/src/main/kotlin',             moduleGroup: 'plugins' }
  - { name: 'orchid-groovydoc-feature',          sourceDirs: '../../../../features/orchid-groovydoc-feature/src/main/kotlin',          moduleGroup: 'plugins' }
  - { name: 'orchid-javadoc-feature',            sourceDirs: '../../../../features/orchid-javadoc-feature/src/main/kotlin',            moduleGroup: 'plugins' }
  - { name: 'orchid-kotlindoc-feature',          sourceDirs: '../../../../features/orchid-kotlindoc-feature/src/main/kotlin',          moduleGroup: 'plugins' }
  - { name: 'orchid-kss-feature',                sourceDirs: '../../../../features/orchid-kss-feature/src/main/kotlin',                moduleGroup: 'plugins' }
  - { name: 'orchid-netlify-cms-feature',        sourceDirs: '../../../../features/orchid-netlify-cms-feature/src/main/kotlin',        moduleGroup: 'plugins' }
  - { name: 'orchid-netlify-feature',            sourceDirs: '../../../../features/orchid-netlify-feature/src/main/kotlin',            moduleGroup: 'plugins' }
  - { name: 'orchid-pages-feature',              sourceDirs: '../../../../features/orchid-pages-feature/src/main/kotlin',              moduleGroup: 'plugins' }
  - { name: 'orchid-plugin-docs-feature',        sourceDirs: '../../../../features/orchid-plugin-docs-feature/src/main/kotlin',        moduleGroup: 'plugins' }
  - { name: 'orchid-posts-feature',              sourceDirs: '../../../../features/orchid-posts-feature/src/main/kotlin',              moduleGroup: 'plugins' }
  - { name: 'orchid-presentations-feature',      sourceDirs: '../../../../features/orchid-presentations-feature/src/main/kotlin',      moduleGroup: 'plugins' }
  - { name: 'orchid-search-feature',             sourceDirs: '../../../../features/orchid-search-feature/src/main/kotlin',             moduleGroup: 'plugins' }
  - { name: 'orchid-snippets-feature',           sourceDirs: '../../../../features/orchid-snippets-feature/src/main/kotlin',           moduleGroup: 'plugins' }
  - { name: 'orchid-sourcedoc-feature',          sourceDirs: '../../../../features/orchid-sourcedoc-feature/src/main/kotlin',          moduleGroup: 'plugins' }
  - { name: 'orchid-swagger-feature',            sourceDirs: '../../../../features/orchid-swagger-feature/src/main/kotlin',            moduleGroup: 'plugins' }
  - { name: 'orchid-swiftdoc-feature',           sourceDirs: '../../../../features/orchid-swiftdoc-feature/src/main/kotlin',           moduleGroup: 'plugins' }
  - { name: 'orchid-syntax-highlighter-feature', sourceDirs: '../../../../features/orchid-syntax-highlighter-feature/src/main/kotlin', moduleGroup: 'plugins' }
  - { name: 'orchid-wiki-feature',               sourceDirs: '../../../../features/orchid-wiki-feature/src/main/kotlin',               moduleGroup: 'plugins' }
  - { name: 'orchid-writers-blocks-feature',     sourceDirs: '../../../../features/orchid-writers-blocks-feature/src/main/kotlin',     moduleGroup: 'plugins' }
  - { name: 'orchid-bsdoc-theme',                sourceDirs: '../../../../themes/orchid-bsdoc-theme/src/main/kotlin',                  moduleGroup: 'themes' }
  - { name: 'orchid-copper-theme',               sourceDirs: '../../../../themes/orchid-copper-theme/src/main/kotlin',                 moduleGroup: 'themes' }
  - { name: 'orchid-editorial-theme',            sourceDirs: '../../../../themes/orchid-editorial-theme/src/main/kotlin',              moduleGroup: 'themes' }
  - { name: 'orchid-future-imperfect-theme',     sourceDirs: '../../../../themes/orchid-future-imperfect-theme/src/main/kotlin',       moduleGroup: 'themes' }
  - { name: 'orchid-all-bundle',                 sourceDirs: '../../../../bundles/orchid-all-bundle/src/main/kotlin',                  moduleGroup: 'bundles' }
  - { name: 'orchid-blog-bundle',                sourceDirs: '../../../../bundles/orchid-blog-bundle/src/main/kotlin',                 moduleGroup: 'bundles' }
  - { name: 'orchid-docs-bundle',                sourceDirs: '../../../../bundles/orchid-docs-bundle/src/main/kotlin',                 moduleGroup: 'bundles' }
  - { name: 'orchid-languages-bundle',           sourceDirs: '../../../../bundles/orchid-languages-bundle/src/main/kotlin',            moduleGroup: 'bundles' }

pages:
  layoutConfig:
    wrapPageInBox: false
    wrapTitleInBox: false
    includeTitle: true
    includeBreadcrumbs: true

moduleHomePages:
  vcsUrl: https://github.com/orchidhq/orchid
  vcsIcon: github
  vcsRepo: orchidhq/orchid
  tags:
    - 'official'
  menu:
    - type: 'separator'
      title: 'All Plugins'
      order: 1000
    - type: 'collectionPages'
      collectionType: 'kotlindoc'
      collectionId: 'modules-plugins'
      order: 1010
    - type: 'separator'
      title: 'All Themes'
      order: 1020
    - type: 'collectionPages'
      collectionType: 'kotlindoc'
      collectionId: 'modules-themes'
      order: 1030
  layoutConfig:
    pageContentsMenu:
      - type: 'separator'
        title: 'In This Page'
      - type: 'pageIds'
        structure: nested
        maxLevel: 2

themesModuleHomePages:
  menu:
    - type: 'separator'
      title: 'Demos'
    - type: 'pageChildren'

classesPages:
  menu:
    - type: 'sourcedocPageLinks'
      includeItems: true
      itemTitleType: "SIGNATURE"

packagesPages:
  menu:
    - type: 'sourcedocPageLinks'
      includeItems: true
